FORMAT: 1A

# IOTAL API
This is the api documentation for react app

# Group Users

Resources related to users in the API

## Question Collection [/users]

### List All Users [GET]

+ Response 200 (application/json)

  []
